### ISSUE TITLE
3.0.2 version breaks build, 1.0.16 works fine

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/nativescript-fresco#39]
When upgraded to 3.0.2:

```
Found peer TypeScript 2.1.6
node_modules/nativescript-fresco/index.d.ts(1,29): error TS2306: File 'D:/www/test/node_modules/tns-core-modules/ui/core/view.d.ts' is not a module.
```

NS: 2.5.3

package.json:
```
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "nativescript-angular": "1.5.2",
    "nativescript-angular-snapshot": "1.5.2-5.5.372.32",
    "nativescript-camera": "0.0.8",
    "nativescript-fresco": "3.0.2",
    "nativescript-geolocation": "0.0.19",
    "nativescript-gif": "1.0.9",
    "nativescript-google-maps-sdk": "1.4.3",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-phone": "1.3.0",
    "nativescript-vibrate": "1.1.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.3.0",
    "tns-core-modules": "2.5.2"
  },
```

**Comment by DJilanov** [comment]
Breaks here too... any suggestions how to get it working ?

**Comment by dxshindeo** [comment]
This might be the cause: `npm WARN nativescript-fresco@3.0.2 requires a peer of tns-core-modules@^3.0.0 || ^3.0.0-rc.1 but none was installed.`

**Comment by brunohenriquesk1** [comment]
its because you have to update your native script to the 3.0 rc then it will work
check this link to update [https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today](url)

**Comment by VladimirAmiorkov** [comment]
Hi all,

The ^3.0.0 version of the nativescript-fresco plugin brings support for NativeScript 3.0. This means that due to the breaking changes of {N} 3.0, this version is not compatible with 2.x.x versions of NativeScript.

If you want to use NativeScript pre 3.0 simply use any of the previous versions of nativescript-fresco like this latest "1.0.16":

`"nativescript-fresco": "1.0.16"`
